spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cau_demo
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
